# Generated by Django 4.2 on 2023-08-06 03:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GetTemperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('hora', models.DateTimeField(default=datetime.datetime(2023, 8, 6, 0, 56, 6, 591947))),
            ],
        ),
        migrations.CreateModel(
            name='SetTemperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_on', models.BooleanField(default=False)),
                ('max_temp', models.IntegerField(default=40)),
                ('hora', models.DateTimeField(default=datetime.datetime(2023, 8, 6, 0, 56, 6, 592945))),
            ],
        ),
    ]
