# Generated by Django 4.2 on 2023-08-06 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gettemperatura',
            name='hora',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 6, 1, 35, 48, 745026)),
        ),
        migrations.AlterField(
            model_name='settemperatura',
            name='hora',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 6, 1, 35, 48, 745026)),
        ),
    ]
